on: push
name: Test

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - run: |
        echo bash -v
        which bash
    - uses: actions/checkout@master
    - uses: actions/setup-node@main
      with:
        node-version: 18
    - run: npm ci
    - run: npm test
