on: push
name: Test

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@main
      with:
        node-version: 18
    - run: npm ci
    - run: npm test
